// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwNeF9k0E2hj6TUJYjDcNc9PUnTCrrWDA',
    appId: '1:645573363922:web:7cab478d28076f8aba850b',
    messagingSenderId: '645573363922',
    projectId: 'pulmopal-aa8df',
    authDomain: 'pulmopal-aa8df.firebaseapp.com',
    storageBucket: 'pulmopal-aa8df.appspot.com',
    measurementId: 'G-FZFX52PX72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGj312KDq6KvVJx6_4Ri5tbZZWtd-x7DQ',
    appId: '1:645573363922:android:7d51bfac1327c1feba850b',
    messagingSenderId: '645573363922',
    projectId: 'pulmopal-aa8df',
    storageBucket: 'pulmopal-aa8df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSHktd-N359LBSVkt70rmJaauYRkTx_TQ',
    appId: '1:645573363922:ios:0969156b84a62a06ba850b',
    messagingSenderId: '645573363922',
    projectId: 'pulmopal-aa8df',
    storageBucket: 'pulmopal-aa8df.appspot.com',
    iosBundleId: 'com.example.pulmopal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSHktd-N359LBSVkt70rmJaauYRkTx_TQ',
    appId: '1:645573363922:ios:8889006ad7d5b157ba850b',
    messagingSenderId: '645573363922',
    projectId: 'pulmopal-aa8df',
    storageBucket: 'pulmopal-aa8df.appspot.com',
    iosBundleId: 'com.example.pulmopal.RunnerTests',
  );
}
